{{- range $key, $val := $.Values.subscriptions }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $key }}
  namespace: openshift-operators
spec:
  channel: {{ $val.channel }}
  installPlanApproval: {{ $val.installPlanApproval }}
  name: {{ $val.package }}
  source: {{ $.Values.catalogSource.name }}
  sourceNamespace: {{ $.Values.catalogSource.namespace }}
  startingCSV: {{ $val.startingCSV }}
{{- end }}
